version: "3.8"

services:
  backend:
    build: ./backend
    container_name: laravel_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    environment:
      - APP_ENV=local
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: angular_frontend
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./frontend:/app
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend:/var/www
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
